module.exports = {
  apps: [
    {
      name: "nutry-server",
      cwd: "./server",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 4003,
      },
      env_production: {
        NODE_ENV: "production",
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      error_file: "/root/.pm2/logs/nutry-server-error.log",
      out_file: "/root/.pm2/logs/nutry-server-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
    {
      name: "nutry-client",
      cwd: "./client",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 3003,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "800M",
      error_file: "/root/.pm2/logs/nutry-client-error.log",
      out_file: "/root/.pm2/logs/nutry-client-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
    {
      name: "nutry-front",
      cwd: "./front",
      script: "npm",
      args: "run preview -- --port 4176 --host 0.0.0.0",
      env: {
        NODE_ENV: "production",
        PORT: 4176,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      error_file: "/root/.pm2/logs/nutry-front-error.log",
      out_file: "/root/.pm2/logs/nutry-front-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
  ],
};
